#!/bin/bash
# Episode title should be primary key
# Rating of episodes

DATABASE=imdb
USERNAME=postgres
HOSTNAME=localhost
export PGPASSWORD=     

psql -h $HOSTNAME -U $USERNAME $DATABASE << EOF
\c imdb
CREATE TABLE TITLE_BASICS(\
		TID  VARCHAR(11)	PRIMARY KEY	NOT NULL,\
		TYPE		TEXT		NOT NULL,\
		ORIGINALNAME		TEXT		NOT NULL,\
		STARTYEAR		SMALLINT,\
		ENDYEAR		SMALLINT,\
		RUNTIMEMINUTES		SMALLINT,\
		CERTIFICATE	VARCHAR(2));
CREATE TABLE PERSON(\
		PID	VARCHAR(11)	PRIMARY KEY	NOT NULL,\
		NAME		TEXT		NOT NULL,\
		BIRTHYEAR		SMALLINT,\
		DEATHYEAR		SMALLINT);
CREATE TABLE PERSON_PROFESSION(\
		PID		VARCHAR(11) references PERSON(PID),\
		PROFESSION 	TEXT		NOT NULL);
CREATE TABLE PERSON_POPULARTITLE(\
		PID		VARCHAR(11) references PERSON(PID),\
		TITLE 	VARCHAR(11) references TITLE_BASICS(TID));
CREATE TABLE TITLE_GENRE(\
		TID 		VARCHAR(11) references TITLE_BASICS(TID),\
		GENRE 	TEXT);
CREATE TABLE TITLE_EPISODE(\
		TID 		VARCHAR(11) references TITLE_BASICS(TID),\
		PARENTSERIES 	VARCHAR(11) references TITLE_BASICS(TID),\
		SEASON_NO		SMALLINT,\
		EPISODE_NO 	SMALLINT);
CREATE TABLE TITLE_RELEASE_INFO(\
		TID 		VARCHAR(11) references TITLE_BASICS(TID),\
		REGION	TEXT,\
		REGIOANLNAME	TEXT,\
		LANGUAGE		TEXT,\
		TYPE			TEXT,\
		ATTRIBUTE		TEXT);
CREATE TABLE ACTOR(\
		PID 			VARCHAR(11) references PERSON(PID) 	NOT NULL,\
		TID 			VARCHAR(11) references TITLE_BASICS(TID) 	NOT NULL,\
		ROLE			TEXT);
CREATE TABLE ACTRESS(\
		PID 			VARCHAR(11) references PERSON(PID) 	NOT NULL,\
		TID 			VARCHAR(11) references TITLE_BASICS(TID) 	NOT NULL,\
		ROLE			TEXT);
CREATE TABLE SELF(\
		PID 			VARCHAR(11) references PERSON(PID) 	NOT NULL,\
		TID 			VARCHAR(11) references TITLE_BASICS(TID) 	NOT NULL,\
		ROLE			TEXT);
CREATE TABLE DIRECTOR(\
		PID 			VARCHAR(11) references PERSON(PID) 	NOT NULL,\
		TID 			VARCHAR(11) references TITLE_BASICS(TID) 	NOT NULL,\
		JOB			TEXT);
CREATE TABLE WRITER(\
		PID 			VARCHAR(11) references PERSON(PID) 	NOT NULL,\
		TID 			VARCHAR(11) references TITLE_BASICS(TID) 	NOT NULL,\
		JOB			TEXT);
CREATE TABLE OTHERCREW(\
		PID 			VARCHAR(11) references PERSON(PID) 	NOT NULL,\
		TID 			VARCHAR(11) references TITLE_BASICS(TID) 	NOT NULL,\
		ROLE			TEXT,\
		JOB			TEXT);
CREATE TABLE TITLE_RATINGS(\
		TID  			VARCHAR(11)	references TITLE_BASICS(TID),\
		RATING 			REAL NOT NULL,\
		NO_OF_VOTES 	INTEGER NOT NULL);
CREATE TABLE AWARDS(\
		TID 			VARCHAR(11) references TITLE_BASICS(TID),\
		AWARDNAME 		TEXT NOT NULL,\
		YEAR			INTEGER NOT NULL);
CREATE TABLE COMPANY(\
		CID				INTEGER  	PRIMARY KEY  NOT NULL,\
		NAME	TEXT	NOT NULL);
CREATE TABLE PRODUCTION(\
		CID				INTEGER references COMPANY(CID),\
		TID				VARCHAR(11) references TITLE_BASICS(TID));
CREATE TABLE TITLE_EARNING(\
		TID 			VARCHAR(11) references TITLE_BASICS(TID),\
		INCOME 			INTEGER);
EOF
